[project]
id = "squire"
name = "Squire"
api_url = "http://127.0.0.1:54321"

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
site_url = "http://localhost:8081"
additional_redirect_urls = ["http://localhost:8081"]
enable_anonymous_sign_ins = true

[auth.email]
enable_signup = true
enable_confirmations = false
