# Configuração local do Supabase CLI — https://supabase.com/docs/guides/local-development/cli/config

project_id = "squire"

[api]
enabled = true
port = 54321

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[auth]
site_url = "http://localhost:8081"
additional_redirect_urls = ["http://localhost:8081"]
enable_anonymous_sign_ins = true

[auth.email]
enable_signup = true
enable_confirmations = false
